Repository infobloxopen/infoblox-client, pull requests merged in 2022-08, with the labels that each got.

#338 Bug NIOS-84387: Fixed response field return logic for the InfobloxObject.create method
  e2e_tests/connector_facade.py
  e2e_tests/test_objects.py
  infoblox_client/objects.py
Labels: bug

#334 Changes to per bug/NIOS-84401
  infoblox_client/objects.py
Labels: bug

#342 Regenerated objects.py module
  infoblox_client/objects.py
Labels: enhancement

#343 Fixed minor Sphinx warnings
  .github/workflows/test.yml
  HISTORY.rst
  docs/conf.py
  docs/index.rst
  infoblox_client/connector.py
  infoblox_client/objects.py
Labels: enhancement, documentation

#344 Bump version to 0.5.1
  HISTORY.rst
  infoblox_client/connector.py
  tests/test_connector.py
Labels: documentation
